apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-connect-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-connect

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-connect-server-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-connect-server

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-connect-spawner-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-connect-spawner

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-consul-server-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-consul-server

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-content-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-content

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-credentials-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-credentials

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-agent-server-colocated-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-agent-server-colocated

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-agent-services-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-agent-services

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-explorer-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-explorer-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-flows-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-flows

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-mining-models-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-mining-models

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-mining-project-resources-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-mining-project-resources

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-mining-results-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-mining-results

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-mining-risk-models-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-mining-risk-models

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-plans-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-plans

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-quality-services-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-quality-services

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-sources-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-sources

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-data-studio-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-data-studio-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-decisions-runtime-builder-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-decisions-runtime-builder

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-deployment-data-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-deployment-data

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-device-management-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-device-management

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-discovery-services-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-discovery-services

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-drive-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-drive-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-environment-manager-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-environment-manager-app

# Adicione o restante dos pods da mesma forma
