apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-workflow-engine-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-workflow-engine
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-workflow-history-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-workflow-history
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-workflow-manager-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-workflow-manager-app
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-workload-orchestrator-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-workload-orchestrator
