apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-feature-flags-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-feature-flags

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-file-store-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-file-store

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-files-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-files

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-formats-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-formats

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-geography-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-geography

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-graph-builder-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-graph-builder-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-graph-templates-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-graph-templates

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-identities-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-identities

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-information-catalog-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-information-catalog-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-insights-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-insights

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-job-execution-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-job-execution

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-job-execution-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-job-execution-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-job-flow-scheduling-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-job-flow-scheduling

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-landing-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-landing-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-launcher-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-launcher

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-launcher-job-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-launcher-job

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-lineage-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-lineage-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-localization-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-localization

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-logon-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-logon-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-microanalytic-score-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-microanalytic-score

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-ml-pipeline-automation-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-ml-pipeline-automation

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-model-management-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-model-management

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-model-manager-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-model-manager-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-model-publish-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-model-publish

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-model-repository-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-model-repository

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-model-studio-app-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-model-studio-app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sas-natural-language-generation-pdb
  namespace: viya4
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sas-natural-language-generation

# Continuar com os próximos pods...
